
# 실습 과제1: NumPy를 활용한 행렬 변형 실습

## 문제 1: 난수 행렬 생성
- N = 6과 M = 5로 설정하고, 0과 1 사이의 난수를 사용하여 (N, M) 형태의 행렬 A를 생성하세요.
- 힌트: np.random.rand() 함수를 사용하세요.

In [21]:
import numpy as np

In [22]:
np.random.seed(42)

N, M = 6, 5
A = np.random.rand(N, M)  # (N, M) 형태

print(A.shape)
print(A)

(6, 5)
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]
 [0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]]


## 문제 2: 새로운 축 추가
- 행렬 A에 np.newaxis를 사용하여 새로운 축을 추가하고, 결과를 B에 저장하세요. B의 형태는 (N, 1, M)이 되어야 합니다.



In [17]:
B = A[:, np.newaxis, :]
assert B.shape == (N, 1, M)

print(B.shape)
print(B[2, 0, :])

(6, 1, 5)
[0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]


## 문제 3: 슬라이싱을 이용한 특정 요소 변경
- 행렬 B에서 세 번째 행의 모든 열을 슬라이싱하여 값을 0.3으로 변경하세요.



In [18]:
B[2, :, :] = 0.3

print(B.shape)
print(B[2, 0, :])

(6, 1, 5)
[0.3 0.3 0.3 0.3 0.3]


## 문제 4: 축 위치를 다르게 설정하여 새로운 행렬 생성
- np.newaxis를 사용하여 A의 형태를 (1, N, M)로 변형한 결과를 C에 저장하고, (N, M, 1)로 변형한 결과를 D에 저장하세요. 각 행렬의 형태를 출력하여 확인하세요.

In [19]:
# (1, N, M)
C = A[np.newaxis, :, :]
# (N, M, 1)
D = A[:, :, np.newaxis]

print(C.shape)
print(D.shape)

(1, 6, 5)
(6, 5, 1)


## 문제 5: 슬라이싱을 통해 부분 행렬 변경
- 행렬 D에서 마지막 세 행의 모든 요소를 0.8로 변경하세요.

In [20]:
D[-3:, :, :] = 0.8

print(D[-3:, :, :].squeeze())

[[0.8 0.8 0.8 0.8 0.8]
 [0.8 0.8 0.8 0.8 0.8]
 [0.8 0.8 0.8 0.8 0.8]]
