# Numpy 기초

## 1. 배열 생성 & 속성 지정

In [27]:
import numpy as np

np.random.seed(0)

# 배열 생성

# 0으로 채워진 길이 10의 배열 생성
y = np.zeros(10, dtype=int) # 타입 미지정시 floot
print(y, "\n")

# 1로 채워진 2차원 floot 배열
y1 = np.ones((3, 5))
print(y1, "\n")

# 3.14로 채워진 3차원 floot 배열
y2 = np.full((3, 3, 2), 3.14)
print(y2, "\n")

[0 0 0 0 0 0 0 0 0 0] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[[3.14 3.14]
  [3.14 3.14]
  [3.14 3.14]]

 [[3.14 3.14]
  [3.14 3.14]
  [3.14 3.14]]

 [[3.14 3.14]
  [3.14 3.14]
  [3.14 3.14]]] 



In [30]:
# ----- 선형 수열로 채운 배열 생성 -----------
# np.arange(start num, finish num, step)
y4 = np.arange(10) # 0부터 10까지 1씩 올라가는 함수
print(x, "\n")


# np.linspace(sNum, fNum, n)
# start num ~ finish num 사이를 n구간 만큼의 값으로 채운 배열 생성
y5 = np.linspace(0, 1, 5) # 소수점 2자리까지 표현됨.
print(y5)


[0 1 2 3 4 5 6 7 8 9] 

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# ---- 균등하게 분포된 배열------- #
# 0과 1사이의 난수로 이루어진 배열
y6 = np.

## 2. 배열 인덱싱 & 슬라이싱

In [ ]:
# 1차원 / 10 사이의 숫자 중 랜덤으로 들어간 6칸짜리 배열을 만들어라
x1 = np.random.randint(10, size=6)
print(x1, "\n")


# 2차원
x2 = np.random.randint(10, size=(3, 4))
print(x2, "\n")


# 3차원
x3 = np.random.randint(10, size=(3, 4, 3))
print(x3)

In [19]:
print(x1[0])
print(x2[0, 0], "\n")

# 슬라이싱
# x[start:stop:step]

# 1차원배열
print(x1[0:4:1])
print(x1[::-1]) # 모든 요소 거꾸로 나열

# 2차원 배열
print()


5
3 

[5 0 3 3]
[9 7 3 3 0 5]

